### PR TITLE
Add a `is_deployed` switch that modifies home page

### PR DESCRIPTION
**Pull request by simeoncarstens**
That way, we can easily change the home page depending on whether a backend deployment is available or not. Here's how it looks like if `is_deployed` is set to `false` in `next.config.js`:
image
So the switch removes the navigation bar and the "give it a whirl" button. Not super pretty / original, but informative.

This also adds a link to the Chainsail repository and more blog post links.

### CODE REVIEW

**Review by dorranh — COMMENTED** [review]
Hey! In principal I think this makes sense, however I think we might still be missing one thing. As far as I can tell, when deployed with this switch set to false the front-end will still contain the pages for jobs, login, etc. (there just is not a way to navigate to them). To be as clear as possible we should likely only include the index page in this case. I'm actually not sure how to do this in NextJS, but perhaps there is an option we can use to control which source files / pages are included in the build.

**Comment by simeoncarstens** [comment]
@dorranh you are absolutely right, the pages would still be available and it would be much cleaner to disable them somehow. It seems that there is in fact a possibility to exclude pages from the build, via `pageExtensions`: https://stackoverflow.com/a/66931617/1656472 but that would necessitate renaming, e.g., `job.js -> job.deployment.js` so that we can exclude the `deployment.js` extension. It doesn't really feel right, to be honest.
I could spend some additional time making rendering of job, dashboard etc. dependent on the `is_deployed` switch.

**Comment by simeoncarstens** [comment]
How about https://github.com/tweag/chainsail/commit/eb628f3? This now just renders a message "Chainsail is currently not deployed under this URL" for the job / dash / results page if `is_deployed` is `false`.

**Review by dorranh — APPROVED** [review]
Given the urgent need to get this deployed in coordination with the blog post I think this works as a temporary work-around. In the future we could maybe consider replacing the `chainsail.io` page with a project documentation page and remove this flag entirely, but I think this works until then.

**Comment by simeoncarstens** [comment]
Yes, I agree. An actual project (documentation) page à la https://jupyenv.io/ or the like would be great, but is a bigger project.

**Pull request merged**
